Contact message
aldaitzwild/Metis_Cooking pull request #15
Opened 2021-04-19 20:15 UTC by Lulu-Soso

Do you agree with this?

"add message errors and validation in contact page and home index"

2021-04-20 07:47 UTC, aldaitzwild requested changes

2021-04-20 07:47 UTC, aldaitzwild commented on src/Controller/ContactController.php
> +                $comment = $_POST['comment'];
Almost perfect ! You just forgot to check the data from the form. Look at htmlentities() to see how to prevent code injection attack.

2021-04-20 09:34 UTC, Lulu-Soso commented on src/Controller/ContactController.php
> +                $comment = $_POST['comment'];
ok i'll check this!

2021-04-21 08:44 UTC, aldaitzwild approved these changes

2021-04-21 08:44 UTC, merged