displays errors if user already subscribe
aldaitzwild/Metis_Cooking pull request #22
Opened 2021-04-28 12:22 UTC by Lulu-Soso

do you agree with this?

2021-04-28 15:29 UTC, aldaitzwild requested changes

2021-04-28 15:29 UTC, aldaitzwild commented on src/Model/SignupManager.php
> +
Insert1 ??? What is this name ??? Is this method used anywhere ? If as I suspect it's not, you delete this part : We don't keep unused code.

2021-04-28 17:11 UTC, Lulu-Soso commented on src/Model/SignupManager.php
> +
ok, i forgot to delete this unused code.

2021-04-29 12:48 UTC, aldaitzwild approved these changes

2021-04-29 12:48 UTC, merged