Us contact messages
aldaitzwild/Metis_Cooking pull request #24
Opened 2021-04-28 14:51 UTC by Marcel-Cathelin

Add the page contact.

2021-04-28 15:32 UTC, aldaitzwild requested changes

2021-04-28 15:32 UTC, aldaitzwild commented on src/Controller/ContactController.php
> +                 Nous vous recontacerons rapidement.";
Typo : Nous vous recontacerons rapidement => Nous vous recontacterons rapidement

2021-04-28 15:32 UTC, aldaitzwild commented on src/View/Login/form.html.twig
> +>>>>>>> origin/dev
This is a conflict ! It shouldn't have been committed  ! Fix it

2021-04-28 19:19 UTC, Marcel-Cathelin commented
I made the changes as request.

2021-04-29 08:48 UTC, aldaitzwild requested changes

2021-04-29 08:48 UTC, aldaitzwild commented on Sauvegarde de ContactManager php.txt
> +$userId = $this->pdo->lastInsertId();
What is this file ??? You don't put backup file in a dev project !

2021-04-29 11:42 UTC, Marcel-Cathelin commented
Delete the .txt file.

2021-04-29 12:48 UTC, aldaitzwild approved these changes

2021-04-29 12:48 UTC, merged